name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }} .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app:latest .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/your-app:latest
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
    
    - name: Deploy to Kubernetes
      run: |
        # Update image tags
        sed -i "s|your-dockerhub-username/your-app:latest|${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}|g" k8s/fastapi-deployment.yaml
        sed -i "s|your-dockerhub-username/your-app:latest|${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}|g" k8s/streamlit-deployment.yaml
        
        # Apply all Kubernetes manifests
        kubectl apply -f k8s/
        
        # Wait for deployments to complete
        kubectl rollout status deployment/fastapi-deployment
        kubectl rollout status deployment/streamlit-deployment
        kubectl rollout status deployment/nginx-deployment